// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ECSDemo {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using UniRx;
    using uFrame.Kernel;
    using ECSDemo;
    
    
    [uFrame.Attributes.uFrameIdentifier("6f4b5006-a62c-4b72-9801-486e3796dab7")]
    public partial class FightSystem : uFrame.ECS.EcsSystem {
        
        private IEcsComponentManagerOf<HealthComponent> _HealthComponentManager;
        
        private IEcsComponentManagerOf<AttackComponent> _AttackComponentManager;
        
        private IEcsComponentManagerOf<TargetComponent> _TargetComponentManager;
        
        private IEcsComponentManagerOf<ArmorComponent> _ArmorComponentManager;
        
        private IEcsComponentManagerOf<AttackingEntity> _AttackingEntityManager;
        
        private IEcsComponentManagerOf<DefendingEntity> _DefendingEntityManager;
        
        private FightSystemPointerClickHandler FightSystemPointerClickHandlerInstance = new FightSystemPointerClickHandler();
        
        public IEcsComponentManagerOf<HealthComponent> HealthComponentManager {
            get {
                return _HealthComponentManager;
            }
            set {
                _HealthComponentManager = value;
            }
        }
        
        public IEcsComponentManagerOf<AttackComponent> AttackComponentManager {
            get {
                return _AttackComponentManager;
            }
            set {
                _AttackComponentManager = value;
            }
        }
        
        public IEcsComponentManagerOf<TargetComponent> TargetComponentManager {
            get {
                return _TargetComponentManager;
            }
            set {
                _TargetComponentManager = value;
            }
        }
        
        public IEcsComponentManagerOf<ArmorComponent> ArmorComponentManager {
            get {
                return _ArmorComponentManager;
            }
            set {
                _ArmorComponentManager = value;
            }
        }
        
        public IEcsComponentManagerOf<AttackingEntity> AttackingEntityManager {
            get {
                return _AttackingEntityManager;
            }
            set {
                _AttackingEntityManager = value;
            }
        }
        
        public IEcsComponentManagerOf<DefendingEntity> DefendingEntityManager {
            get {
                return _DefendingEntityManager;
            }
            set {
                _DefendingEntityManager = value;
            }
        }
        
        public override void Setup() {
            base.Setup();
            AttackingEntityManager = ComponentSystem.RegisterGroup<AttackingEntityGroup,AttackingEntity>();
            DefendingEntityManager = ComponentSystem.RegisterGroup<DefendingEntityGroup,DefendingEntity>();
            HealthComponentManager = ComponentSystem.RegisterComponent<HealthComponent>();
            AttackComponentManager = ComponentSystem.RegisterComponent<AttackComponent>();
            TargetComponentManager = ComponentSystem.RegisterComponent<TargetComponent>();
            ArmorComponentManager = ComponentSystem.RegisterComponent<ArmorComponent>();
            this.OnEvent<uFrame.ECS.PointerClickDispatcher>().Subscribe(_=>{ FightSystemPointerClickFilter(_); }).DisposeWith(this);
        }
        
        protected void FightSystemPointerClickHandler(uFrame.ECS.PointerClickDispatcher data, AttackingEntity source) {
            var handler = FightSystemPointerClickHandlerInstance;
            handler.System = this;
            handler.Event = data;
            handler.Source = source;
            StartCoroutine(handler.Execute());
        }
        
        protected void FightSystemPointerClickFilter(uFrame.ECS.PointerClickDispatcher data) {
            var SourceItem = AttackingEntityManager[data.EntityId];
            if (SourceItem == null) {
                return;
            }
            if (!SourceItem.Enabled) {
                return;
            }
            this.FightSystemPointerClickHandler(data, SourceItem);
        }
    }
}
