// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ECSDemo {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using uFrame.ECS;
    using UniRx;
    
    
    [uFrame.Attributes.uFrameIdentifier("98c8d034-f6e0-452f-8430-19cca0c800c8")]
    public partial class AttackComponent : uFrame.ECS.EcsComponent {
        
        [UnityEngine.SerializeField()]
        private Int32 _MaxDamage;
        
        [UnityEngine.SerializeField()]
        private Int32 _MinDamage;
        
        private Subject<PropertyChangedEvent<Int32>> _MaxDamageObservable;
        
        private PropertyChangedEvent<Int32> _MaxDamageEvent;
        
        private Subject<PropertyChangedEvent<Int32>> _MinDamageObservable;
        
        private PropertyChangedEvent<Int32> _MinDamageEvent;
        
        public int ComponentID {
            get {
                return 26;
            }
        }
        
        public IObservable<PropertyChangedEvent<Int32>> MaxDamageObservable {
            get {
                return _MaxDamageObservable ?? (_MaxDamageObservable = new Subject<PropertyChangedEvent<Int32>>());
            }
        }
        
        public IObservable<PropertyChangedEvent<Int32>> MinDamageObservable {
            get {
                return _MinDamageObservable ?? (_MinDamageObservable = new Subject<PropertyChangedEvent<Int32>>());
            }
        }
        
        public Int32 MaxDamage {
            get {
                return _MaxDamage;
            }
            set {
                SetMaxDamage(value);
            }
        }
        
        public Int32 MinDamage {
            get {
                return _MinDamage;
            }
            set {
                SetMinDamage(value);
            }
        }
        
        public virtual void SetMaxDamage(Int32 value) {
            SetProperty(ref _MaxDamage, value, ref _MaxDamageEvent, _MaxDamageObservable);
        }
        
        public virtual void SetMinDamage(Int32 value) {
            SetProperty(ref _MinDamage, value, ref _MinDamageEvent, _MinDamageObservable);
        }
    }
}
