// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ECSDemo {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using uFrame.ECS;
    using UniRx;
    
    
    [uFrame.Attributes.uFrameIdentifier("98c8d034-f6e0-452f-8430-19cca0c800c8")]
    public partial class AttackComponent : uFrame.ECS.EcsComponent {
        
        [UnityEngine.SerializeField()]
        private Int32 _Damage;
        
        private Subject<PropertyChangedEvent<Int32>> _DamageObservable;
        
        private PropertyChangedEvent<Int32> _DamageEvent;
        
        public int ComponentID {
            get {
                return 2;
            }
        }
        
        public IObservable<PropertyChangedEvent<Int32>> DamageObservable {
            get {
                return _DamageObservable ?? (_DamageObservable = new Subject<PropertyChangedEvent<Int32>>());
            }
        }
        
        public Int32 Damage {
            get {
                return _Damage;
            }
            set {
                SetDamage(value);
            }
        }
        
        public virtual void SetDamage(Int32 value) {
            SetProperty(ref _Damage, value, ref _DamageEvent, _DamageObservable);
        }
    }
}
