// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ECSDemo {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using uFrame.ECS;
    using UniRx;
    
    
    [uFrame.Attributes.uFrameIdentifier("385ae253-d5f1-4762-8cbd-fe4e52d94d75")]
    public partial class HealthComponent : uFrame.ECS.EcsComponent {
        
        [UnityEngine.SerializeField()]
        private Int32 _Health;
        
        private Subject<PropertyChangedEvent<Int32>> _HealthObservable;
        
        private PropertyChangedEvent<Int32> _HealthEvent;
        
        public int ComponentID {
            get {
                return 1;
            }
        }
        
        public IObservable<PropertyChangedEvent<Int32>> HealthObservable {
            get {
                return _HealthObservable ?? (_HealthObservable = new Subject<PropertyChangedEvent<Int32>>());
            }
        }
        
        public Int32 Health {
            get {
                return _Health;
            }
            set {
                SetHealth(value);
            }
        }
        
        public virtual void SetHealth(Int32 value) {
            SetProperty(ref _Health, value, ref _HealthEvent, _HealthObservable);
        }
    }
}
