// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ECSDemo {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class DamageSystemEntityAttackedHandler {
        
        public AttackingEntity Attacker;
        
        public DefendingEntity Defender;
        
        private ECSDemo.EntityAttacked _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private int ActionNode21_min = default( System.Int32 );
        
        private int ActionNode21_max = default( System.Int32 );
        
        private int ActionNode21_Result = default( System.Int32 );
        
        private int ActionNode23_a = default( System.Int32 );
        
        private int ActionNode23_b = default( System.Int32 );
        
        private int ActionNode23_Result = default( System.Int32 );
        
        private int ActionNode28_in = default( System.Int32 );
        
        private float ActionNode28_Result = default( System.Single );
        
        private float ActionNode27_a = default( System.Single );
        
        private int ActionNode29_in = default( System.Int32 );
        
        private int IntNode25 = 0;
        
        private float ActionNode29_Result = default( System.Single );
        
        private float ActionNode27_b = default( System.Single );
        
        private bool ActionNode27_Result = default( System.Boolean );
        
        private int ActionNode6_a = default( System.Int32 );
        
        private int ActionNode6_b = default( System.Int32 );
        
        private int ActionNode6_Result = default( System.Int32 );
        
        private object ActionNode7_message = default( System.Object );
        
        private string StringNode8 = "DamageSystem - Entity health changed.";
        
        private ECSDemo.HealthChanged PublishEventNode9_Result = default( ECSDemo.HealthChanged );
        
        public ECSDemo.EntityAttacked Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual System.Collections.IEnumerator Execute() {
            ActionNode21_min = Attacker.AttackComponent.MinDamage;
            ActionNode21_max = Attacker.AttackComponent.MaxDamage;
            // ActionNode
            while (this.DebugInfo("1de75035-cb19-47f1-800a-142423e8c74f","7f2b22cb-d285-49e0-ad0b-e376f57e5f1a", this) == 1) yield return null;
            // Visit uFrame.Actions.CreateRandoms.RandomInt
            ActionNode21_Result = uFrame.Actions.CreateRandoms.RandomInt(ActionNode21_min, ActionNode21_max);
            ActionNode23_a = ActionNode21_Result;
            ActionNode23_b = Defender.ArmorComponent.Armor;
            // ActionNode
            while (this.DebugInfo("7f2b22cb-d285-49e0-ad0b-e376f57e5f1a","4119d7a7-51be-4a62-a5a4-630b75a5f3c1", this) == 1) yield return null;
            // Visit uFrame.Actions.IntLibrary.Subtract
            ActionNode23_Result = uFrame.Actions.IntLibrary.Subtract(ActionNode23_a, ActionNode23_b);
            ActionNode28_in = ActionNode23_Result;
            // ActionNode
            while (this.DebugInfo("4119d7a7-51be-4a62-a5a4-630b75a5f3c1","9410f9ae-f9cf-4747-ad58-59b9f85dd911", this) == 1) yield return null;
            // Visit uFrame.Actions.Converter.IntToFloat
            ActionNode28_Result = uFrame.Actions.Converter.IntToFloat(ActionNode28_in);
            ActionNode27_a = ActionNode28_Result;
            ActionNode29_in = IntNode25;
            // ActionNode
            while (this.DebugInfo("9410f9ae-f9cf-4747-ad58-59b9f85dd911","07aab690-ab5d-4315-8038-86cf93409be3", this) == 1) yield return null;
            // Visit uFrame.Actions.Converter.IntToFloat
            ActionNode29_Result = uFrame.Actions.Converter.IntToFloat(ActionNode29_in);
            ActionNode27_b = ActionNode29_Result;
            // ActionNode
            while (this.DebugInfo("07aab690-ab5d-4315-8038-86cf93409be3","592f2d04-7d9d-4c15-b70b-e415b97a1e7d", this) == 1) yield return null;
            // Visit uFrame.Actions.Comparisons.GreaterThan
            ActionNode27_Result = uFrame.Actions.Comparisons.GreaterThan(ActionNode27_a, ActionNode27_b, ()=> { System.StartCoroutine(ActionNode27_yes()); }, ()=> { System.StartCoroutine(ActionNode27_no()); });
            yield break;
        }
        
        private System.Collections.IEnumerator ActionNode27_yes() {
            ActionNode6_a = Defender.HealthComponent.Health;
            ActionNode6_b = ActionNode23_Result;
            // ActionNode
            while (this.DebugInfo("592f2d04-7d9d-4c15-b70b-e415b97a1e7d","a010da49-1016-4be7-af66-635fb9568f51", this) == 1) yield return null;
            // Visit uFrame.Actions.IntLibrary.Subtract
            ActionNode6_Result = uFrame.Actions.IntLibrary.Subtract(ActionNode6_a, ActionNode6_b);
            // SetVariableNode
            while (this.DebugInfo("a010da49-1016-4be7-af66-635fb9568f51","16b8d1d5-e7f3-4b3c-82c0-ffdb0700577a", this) == 1) yield return null;
            Defender.HealthComponent.Health = (System.Int32)ActionNode6_Result;
            ActionNode7_message = StringNode8;
            // ActionNode
            while (this.DebugInfo("16b8d1d5-e7f3-4b3c-82c0-ffdb0700577a","ac96668a-7e2c-476d-afa5-b264faa1e1cf", this) == 1) yield return null;
            // Visit uFrame.Actions.DebugLibrary.LogMessage
            uFrame.Actions.DebugLibrary.LogMessage(ActionNode7_message);
            // PublishEventNode
            while (this.DebugInfo("ac96668a-7e2c-476d-afa5-b264faa1e1cf","bd50d6fa-13a8-4a2a-bfa2-e0edc11d9af1", this) == 1) yield return null;
            var PublishEventNode9_Event = new HealthChanged();
            PublishEventNode9_Event.Instigator = Event.Attacker;
            PublishEventNode9_Event.Health = Defender.HealthComponent.Health;
            PublishEventNode9_Event.Entity = Event.Defender;
            System.Publish(PublishEventNode9_Event);
            PublishEventNode9_Event = PublishEventNode9_Result;
            yield break;
        }
        
        private System.Collections.IEnumerator ActionNode27_no() {
            yield break;
        }
    }
}
