// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ECSDemo {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class DefeatSystemHealthChangedHandler {
        
        public DefendingEntity Entity;
        
        private ECSDemo.HealthChanged _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private int ActionNode12_in = default( System.Int32 );
        
        private float ActionNode12_Result = default( System.Single );
        
        private float ActionNode11_a = default( System.Single );
        
        private int ActionNode14_in = default( System.Int32 );
        
        private int IntNode13 = 0;
        
        private float ActionNode14_Result = default( System.Single );
        
        private float ActionNode11_b = default( System.Single );
        
        private bool ActionNode11_Result = default( System.Boolean );
        
        private int ActionNode15_entityId = default( System.Int32 );
        
        private float ActionNode15_time = default( System.Single );
        
        private object ActionNode16_message = default( System.Object );
        
        private string StringNode17 = "DefeatSystem - Entity destroyed.";
        
        public ECSDemo.HealthChanged Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual System.Collections.IEnumerator Execute() {
            ActionNode12_in = Event.Health;
            // ActionNode
            while (this.DebugInfo("b247b012-b03e-4f3b-aca3-553347375e23","66326511-e9ce-46b2-9ed9-821458c3da3a", this) == 1) yield return null;
            // Visit uFrame.Actions.Converter.IntToFloat
            ActionNode12_Result = uFrame.Actions.Converter.IntToFloat(ActionNode12_in);
            ActionNode11_a = ActionNode12_Result;
            ActionNode14_in = IntNode13;
            // ActionNode
            while (this.DebugInfo("66326511-e9ce-46b2-9ed9-821458c3da3a","2107a8ee-333c-4360-89f4-7ca7c33c85cd", this) == 1) yield return null;
            // Visit uFrame.Actions.Converter.IntToFloat
            ActionNode14_Result = uFrame.Actions.Converter.IntToFloat(ActionNode14_in);
            ActionNode11_b = ActionNode14_Result;
            // ActionNode
            while (this.DebugInfo("2107a8ee-333c-4360-89f4-7ca7c33c85cd","cb73f35b-fde2-4886-b1f9-7b2c55678947", this) == 1) yield return null;
            // Visit uFrame.Actions.Comparisons.LessThanOrEqual
            ActionNode11_Result = uFrame.Actions.Comparisons.LessThanOrEqual(ActionNode11_a, ActionNode11_b, ()=> { System.StartCoroutine(ActionNode11_yes()); }, ()=> { System.StartCoroutine(ActionNode11_no()); });
            yield break;
        }
        
        private System.Collections.IEnumerator ActionNode11_yes() {
            ActionNode15_entityId = Entity.Entity.EntityId;
            // ActionNode
            while (this.DebugInfo("cb73f35b-fde2-4886-b1f9-7b2c55678947","144a6a06-3702-4b89-bb35-04de982263ba", this) == 1) yield return null;
            // Visit uFrame.Actions.DestroyLibrary.DestroyEntity
            uFrame.Actions.DestroyLibrary.DestroyEntity(ActionNode15_entityId, ActionNode15_time);
            ActionNode16_message = StringNode17;
            // ActionNode
            while (this.DebugInfo("144a6a06-3702-4b89-bb35-04de982263ba","c3a09036-50e1-4ac7-a9d4-a7834ee5ec37", this) == 1) yield return null;
            // Visit uFrame.Actions.DebugLibrary.LogMessage
            uFrame.Actions.DebugLibrary.LogMessage(ActionNode16_message);
            yield break;
        }
        
        private System.Collections.IEnumerator ActionNode11_no() {
            yield break;
        }
    }
}
