// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ECSDemo {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class ExperienceSystemEntityDefeatedHandler {
        
        public LevelingEntity Attacker;
        
        private ECSDemo.EntityDefeated _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private int ActionNode33_a = default( System.Int32 );
        
        private int ActionNode33_b = default( System.Int32 );
        
        private int IntNode34 = 100;
        
        private int ActionNode33_Result = default( System.Int32 );
        
        private ECSDemo.ExperienceChanged PublishEventNode35_Result = default( ECSDemo.ExperienceChanged );
        
        private object ActionNode36_message = default( System.Object );
        
        private string StringNode37 = "ExperienceSystem - Experience changed.";
        
        public ECSDemo.EntityDefeated Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual System.Collections.IEnumerator Execute() {
            ActionNode33_a = Attacker.LevelComponent.CurrentXp;
            ActionNode33_b = IntNode34;
            // ActionNode
            while (this.DebugInfo("bd50d6fa-13a8-4a2a-bfa2-e0edc11d9af1","0fb9962a-1974-4637-b02e-cea53a7d49d8", this) == 1) yield return null;
            // Visit uFrame.Actions.IntLibrary.Add
            ActionNode33_Result = uFrame.Actions.IntLibrary.Add(ActionNode33_a, ActionNode33_b);
            // SetVariableNode
            while (this.DebugInfo("0fb9962a-1974-4637-b02e-cea53a7d49d8","af72a918-250a-43df-b213-904bf25a7030", this) == 1) yield return null;
            Attacker.LevelComponent.CurrentXp = (System.Int32)ActionNode33_Result;
            // PublishEventNode
            while (this.DebugInfo("af72a918-250a-43df-b213-904bf25a7030","1df28dab-ef8d-411e-aa03-c20ec32e50fa", this) == 1) yield return null;
            var PublishEventNode35_Event = new ExperienceChanged();
            PublishEventNode35_Event.Entity = Event.Attacker;
            System.Publish(PublishEventNode35_Event);
            PublishEventNode35_Event = PublishEventNode35_Result;
            ActionNode36_message = StringNode37;
            // ActionNode
            while (this.DebugInfo("1df28dab-ef8d-411e-aa03-c20ec32e50fa","97ef28ae-6679-4de0-91c9-e4c02c0d6647", this) == 1) yield return null;
            // Visit uFrame.Actions.DebugLibrary.LogMessage
            uFrame.Actions.DebugLibrary.LogMessage(ActionNode36_message);
            yield break;
        }
    }
}
