// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ECSDemo {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class LevelUpSystemExperienceChangedHandler {
        
        public LevelingEntity Entity;
        
        private ECSDemo.ExperienceChanged _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private int ActionNode40_in = default( System.Int32 );
        
        private float ActionNode40_Result = default( System.Single );
        
        private float ActionNode39_a = default( System.Single );
        
        private int ActionNode41_in = default( System.Int32 );
        
        private float ActionNode41_Result = default( System.Single );
        
        private float ActionNode39_b = default( System.Single );
        
        private bool ActionNode39_Result = default( System.Boolean );
        
        private object ActionNode42_message = default( System.Object );
        
        private string StringNode43 = "LevelUpSystem - Entity leveled up!";
        
        private int ActionNode45_a = default( System.Int32 );
        
        private int ActionNode45_b = default( System.Int32 );
        
        private int IntNode46 = 1;
        
        private int ActionNode45_Result = default( System.Int32 );
        
        private int IntNode48 = 0;
        
        private int ActionNode50_a = default( System.Int32 );
        
        private int ActionNode51_a = default( System.Int32 );
        
        private int ActionNode51_b = default( System.Int32 );
        
        private int IntNode53 = 1;
        
        private int ActionNode51_Result = default( System.Int32 );
        
        private int ActionNode50_b = default( System.Int32 );
        
        private int ActionNode50_Result = default( System.Int32 );
        
        private int ActionNode52_a = default( System.Int32 );
        
        private int ActionNode52_b = default( System.Int32 );
        
        private int IntNode54 = 2;
        
        private int ActionNode52_Result = default( System.Int32 );
        
        private int ActionNode55_a = default( System.Int32 );
        
        private int ActionNode55_b = default( System.Int32 );
        
        private int IntNode56 = 100;
        
        private int ActionNode55_Result = default( System.Int32 );
        
        private int ActionNode58_a = default( System.Int32 );
        
        private int ActionNode58_b = default( System.Int32 );
        
        private int IntNode59 = 10;
        
        private int ActionNode58_Result = default( System.Int32 );
        
        private int ActionNode61_a = default( System.Int32 );
        
        private int ActionNode61_b = default( System.Int32 );
        
        private int IntNode62 = 2;
        
        private int ActionNode61_Result = default( System.Int32 );
        
        public ECSDemo.ExperienceChanged Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual System.Collections.IEnumerator Execute() {
            ActionNode40_in = Entity.LevelComponent.CurrentXp;
            // ActionNode
            while (this.DebugInfo("1de75035-cb19-47f1-800a-142423e8c74f","78baf8ac-be90-4aee-a0d7-babfd8ba2f24", this) == 1) yield return null;
            // Visit uFrame.Actions.Converter.IntToFloat
            ActionNode40_Result = uFrame.Actions.Converter.IntToFloat(ActionNode40_in);
            ActionNode39_a = ActionNode40_Result;
            ActionNode41_in = Entity.LevelComponent.MaxXp;
            // ActionNode
            while (this.DebugInfo("78baf8ac-be90-4aee-a0d7-babfd8ba2f24","486f5d43-3667-496b-86fa-7211f6dd9c32", this) == 1) yield return null;
            // Visit uFrame.Actions.Converter.IntToFloat
            ActionNode41_Result = uFrame.Actions.Converter.IntToFloat(ActionNode41_in);
            ActionNode39_b = ActionNode41_Result;
            // ActionNode
            while (this.DebugInfo("486f5d43-3667-496b-86fa-7211f6dd9c32","c40eab18-0427-441e-85e9-1a1eb3389373", this) == 1) yield return null;
            // Visit uFrame.Actions.Comparisons.GreaterThanOrEqual
            ActionNode39_Result = uFrame.Actions.Comparisons.GreaterThanOrEqual(ActionNode39_a, ActionNode39_b, ()=> { System.StartCoroutine(ActionNode39_yes()); }, ()=> { System.StartCoroutine(ActionNode39_no()); });
            yield break;
        }
        
        private System.Collections.IEnumerator ActionNode39_yes() {
            ActionNode42_message = StringNode43;
            // ActionNode
            while (this.DebugInfo("c40eab18-0427-441e-85e9-1a1eb3389373","d9054f2c-d86a-4377-8860-3e0cfd80e1a7", this) == 1) yield return null;
            // Visit uFrame.Actions.DebugLibrary.LogMessage
            uFrame.Actions.DebugLibrary.LogMessage(ActionNode42_message);
            ActionNode45_a = Entity.LevelComponent.Level;
            ActionNode45_b = IntNode46;
            // ActionNode
            while (this.DebugInfo("d9054f2c-d86a-4377-8860-3e0cfd80e1a7","6fa9cb2e-1915-4c63-a76f-e606dfe054f0", this) == 1) yield return null;
            // Visit uFrame.Actions.IntLibrary.Add
            ActionNode45_Result = uFrame.Actions.IntLibrary.Add(ActionNode45_a, ActionNode45_b);
            // SetVariableNode
            while (this.DebugInfo("6fa9cb2e-1915-4c63-a76f-e606dfe054f0","879dd259-d7d0-4ddc-aed5-360f70962e3c", this) == 1) yield return null;
            Entity.LevelComponent.Level = (System.Int32)ActionNode45_Result;
            // SetVariableNode
            while (this.DebugInfo("879dd259-d7d0-4ddc-aed5-360f70962e3c","fbe3b8d8-ee48-42b1-9cf0-c5fca8af6bc7", this) == 1) yield return null;
            Entity.LevelComponent.CurrentXp = (System.Int32)IntNode48;
            ActionNode50_a = Entity.LevelComponent.Level;
            ActionNode51_a = Entity.LevelComponent.Level;
            ActionNode51_b = IntNode53;
            // ActionNode
            while (this.DebugInfo("fbe3b8d8-ee48-42b1-9cf0-c5fca8af6bc7","6b9b0cb0-cff7-4330-b36b-47e4a9b9126a", this) == 1) yield return null;
            // Visit uFrame.Actions.IntLibrary.Add
            ActionNode51_Result = uFrame.Actions.IntLibrary.Add(ActionNode51_a, ActionNode51_b);
            ActionNode50_b = ActionNode51_Result;
            // ActionNode
            while (this.DebugInfo("6b9b0cb0-cff7-4330-b36b-47e4a9b9126a","0bd2e907-46f3-44b9-8a8a-9828a2169103", this) == 1) yield return null;
            // Visit uFrame.Actions.IntLibrary.Multiply
            ActionNode50_Result = uFrame.Actions.IntLibrary.Multiply(ActionNode50_a, ActionNode50_b);
            ActionNode52_a = ActionNode50_Result;
            ActionNode52_b = IntNode54;
            // ActionNode
            while (this.DebugInfo("0bd2e907-46f3-44b9-8a8a-9828a2169103","3d84d316-0b19-40ce-befc-be79eafd27b8", this) == 1) yield return null;
            // Visit uFrame.Actions.IntLibrary.Divide
            ActionNode52_Result = uFrame.Actions.IntLibrary.Divide(ActionNode52_a, ActionNode52_b);
            ActionNode55_a = ActionNode52_Result;
            ActionNode55_b = IntNode56;
            // ActionNode
            while (this.DebugInfo("3d84d316-0b19-40ce-befc-be79eafd27b8","d0b85c67-0ae3-4bdb-8b17-c5687b5e7d5e", this) == 1) yield return null;
            // Visit uFrame.Actions.IntLibrary.Multiply
            ActionNode55_Result = uFrame.Actions.IntLibrary.Multiply(ActionNode55_a, ActionNode55_b);
            // SetVariableNode
            while (this.DebugInfo("d0b85c67-0ae3-4bdb-8b17-c5687b5e7d5e","9a641b2f-879f-4a1c-8f03-53db4055e282", this) == 1) yield return null;
            Entity.LevelComponent.MaxXp = (System.Int32)ActionNode55_Result;
            ActionNode58_a = Entity.HealthComponent.Health;
            ActionNode58_b = IntNode59;
            // ActionNode
            while (this.DebugInfo("9a641b2f-879f-4a1c-8f03-53db4055e282","0abf7ca7-cea6-483e-bbc9-45109257b3c4", this) == 1) yield return null;
            // Visit uFrame.Actions.IntLibrary.Add
            ActionNode58_Result = uFrame.Actions.IntLibrary.Add(ActionNode58_a, ActionNode58_b);
            // SetVariableNode
            while (this.DebugInfo("0abf7ca7-cea6-483e-bbc9-45109257b3c4","664e4add-08c1-487e-927f-a5fe9db7db58", this) == 1) yield return null;
            Entity.HealthComponent.Health = (System.Int32)ActionNode58_Result;
            ActionNode61_a = Entity.AttackComponent.MaxDamage;
            ActionNode61_b = IntNode62;
            // ActionNode
            while (this.DebugInfo("664e4add-08c1-487e-927f-a5fe9db7db58","344a0f59-9d27-400d-a57a-6aa1123f03c3", this) == 1) yield return null;
            // Visit uFrame.Actions.IntLibrary.Add
            ActionNode61_Result = uFrame.Actions.IntLibrary.Add(ActionNode61_a, ActionNode61_b);
            // SetVariableNode
            while (this.DebugInfo("344a0f59-9d27-400d-a57a-6aa1123f03c3","54dfe765-5ab4-4a05-80d9-20413da2ca51", this) == 1) yield return null;
            Entity.AttackComponent.MaxDamage = (System.Int32)ActionNode61_Result;
            yield break;
        }
        
        private System.Collections.IEnumerator ActionNode39_no() {
            yield break;
        }
    }
}
