// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ECSDemo {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using UniRx;
    using uFrame.Kernel;
    
    
    public partial class AttackingEntityGroup : ReactiveGroup<AttackingEntity> {
        
        private IEcsComponentManagerOf<TargetComponent> _TargetComponentManager;
        
        private IEcsComponentManagerOf<AttackComponent> _AttackComponentManager;
        
        private int lastEntityId;
        
        private TargetComponent TargetComponent;
        
        private AttackComponent AttackComponent;
        
        public IEcsComponentManagerOf<TargetComponent> TargetComponentManager {
            get {
                return _TargetComponentManager;
            }
            set {
                _TargetComponentManager = value;
            }
        }
        
        public IEcsComponentManagerOf<AttackComponent> AttackComponentManager {
            get {
                return _AttackComponentManager;
            }
            set {
                _AttackComponentManager = value;
            }
        }
        
        public override System.Collections.Generic.IEnumerable<UniRx.IObservable<int>> Install(uFrame.ECS.IComponentSystem componentSystem) {
            TargetComponentManager = componentSystem.RegisterComponent<TargetComponent>();
            yield return TargetComponentManager.CreatedObservable.Select(_=>_.EntityId);;
            yield return TargetComponentManager.RemovedObservable.Select(_=>_.EntityId);;
            AttackComponentManager = componentSystem.RegisterComponent<AttackComponent>();
            yield return AttackComponentManager.CreatedObservable.Select(_=>_.EntityId);;
            yield return AttackComponentManager.RemovedObservable.Select(_=>_.EntityId);;
        }
        
        public override bool Match(int entityId) {
            lastEntityId = entityId;
            if ((TargetComponent = TargetComponentManager[entityId]) == null) {
                return false;
            }
            if ((AttackComponent = AttackComponentManager[entityId]) == null) {
                return false;
            }
            return true;
        }
        
        public override AttackingEntity Select() {
            var item = new AttackingEntity();;
            item.EntityId = lastEntityId;
            item.TargetComponent = TargetComponent;
            item.AttackComponent = AttackComponent;
            return item;
        }
    }
}
