// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ECSDemo {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UniRx;
    using uFrame.Kernel;
    using uFrame.ECS;
    
    
    public partial class AttackingEntity : uFrame.ECS.GroupItem {
        
        private TargetComponent _TargetComponent;
        
        private AttackComponent _AttackComponent;
        
        public TargetComponent TargetComponent {
            get {
                return _TargetComponent;
            }
            set {
                _TargetComponent = value;
            }
        }
        
        public AttackComponent AttackComponent {
            get {
                return _AttackComponent;
            }
            set {
                _AttackComponent = value;
            }
        }
        
        public int ComponentID {
            get {
                return 5;
            }
        }
    }
}
