// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ECSDemo {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UniRx;
    using uFrame.Kernel;
    using uFrame.ECS;
    
    
    public partial class DefendingEntity : uFrame.ECS.GroupItem {
        
        private ArmorComponent _ArmorComponent;
        
        private HealthComponent _HealthComponent;
        
        public ArmorComponent ArmorComponent {
            get {
                return _ArmorComponent;
            }
            set {
                _ArmorComponent = value;
            }
        }
        
        public HealthComponent HealthComponent {
            get {
                return _HealthComponent;
            }
            set {
                _HealthComponent = value;
            }
        }
        
        public int ComponentID {
            get {
                return 30;
            }
        }
    }
}
