// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ECSDemo {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UniRx;
    using uFrame.Kernel;
    using uFrame.ECS;
    
    
    public partial class LevelingEntity : uFrame.ECS.GroupItem {
        
        private LevelComponent _LevelComponent;
        
        public LevelComponent LevelComponent {
            get {
                return _LevelComponent;
            }
            set {
                _LevelComponent = value;
            }
        }
        
        public int ComponentID {
            get {
                return 32;
            }
        }
    }
}
