// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ECSDemo {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using UniRx;
    using uFrame.Kernel;
    
    
    public partial class LevelingEntityGroup : ReactiveGroup<LevelingEntity> {
        
        private IEcsComponentManagerOf<HealthComponent> _HealthComponentManager;
        
        private IEcsComponentManagerOf<AttackComponent> _AttackComponentManager;
        
        private IEcsComponentManagerOf<LevelComponent> _LevelComponentManager;
        
        private int lastEntityId;
        
        private HealthComponent HealthComponent;
        
        private AttackComponent AttackComponent;
        
        private LevelComponent LevelComponent;
        
        public IEcsComponentManagerOf<HealthComponent> HealthComponentManager {
            get {
                return _HealthComponentManager;
            }
            set {
                _HealthComponentManager = value;
            }
        }
        
        public IEcsComponentManagerOf<AttackComponent> AttackComponentManager {
            get {
                return _AttackComponentManager;
            }
            set {
                _AttackComponentManager = value;
            }
        }
        
        public IEcsComponentManagerOf<LevelComponent> LevelComponentManager {
            get {
                return _LevelComponentManager;
            }
            set {
                _LevelComponentManager = value;
            }
        }
        
        public override System.Collections.Generic.IEnumerable<UniRx.IObservable<int>> Install(uFrame.ECS.IComponentSystem componentSystem) {
            HealthComponentManager = componentSystem.RegisterComponent<HealthComponent>();
            yield return HealthComponentManager.CreatedObservable.Select(_=>_.EntityId);;
            yield return HealthComponentManager.RemovedObservable.Select(_=>_.EntityId);;
            AttackComponentManager = componentSystem.RegisterComponent<AttackComponent>();
            yield return AttackComponentManager.CreatedObservable.Select(_=>_.EntityId);;
            yield return AttackComponentManager.RemovedObservable.Select(_=>_.EntityId);;
            LevelComponentManager = componentSystem.RegisterComponent<LevelComponent>();
            yield return LevelComponentManager.CreatedObservable.Select(_=>_.EntityId);;
            yield return LevelComponentManager.RemovedObservable.Select(_=>_.EntityId);;
        }
        
        public override bool Match(int entityId) {
            lastEntityId = entityId;
            if ((HealthComponent = HealthComponentManager[entityId]) == null) {
                return false;
            }
            if ((AttackComponent = AttackComponentManager[entityId]) == null) {
                return false;
            }
            if ((LevelComponent = LevelComponentManager[entityId]) == null) {
                return false;
            }
            return true;
        }
        
        public override LevelingEntity Select() {
            var item = new LevelingEntity();;
            item.EntityId = lastEntityId;
            item.HealthComponent = HealthComponent;
            item.AttackComponent = AttackComponent;
            item.LevelComponent = LevelComponent;
            return item;
        }
    }
}
